clear

echo "                                                                         "
echo "                                                                         "
echo "                                                                         "
echo "                                     ▄▄▄      ▓█████▄  ███▄ ▄███▓ ▄▄▄     ▄▄▄█████▓"
echo "                                    ▒████▄    ▒██▀ ██▌▓██▒▀█▀ ██▒▒████▄   ▓  ██▒ ▓▒"
echo "                                    ▒██  ▀█▄  ░██   █▌▓██    ▓██░▒██  ▀█▄ ▒ ▓██░ ▒░"
echo "                                    ░██▄▄▄▄██ ░▓█▄   ▌▒██    ▒██ ░██▄▄▄▄██░ ▓██▓ ░ "
echo "                                     ▓█   ▓██▒░▒████▓ ▒██▒   ░██▒ ▓█   ▓██▒ ▒██▒ ░ "
echo "                                     ▒▒   ▓▒█░ ▒▒▓  ▒ ░ ▒░   ░  ░ ▒▒   ▓▒█░ ▒ ░░ "
echo "                                     ▒   ▒▒ ░ ░ ▒  ▒ ░  ░      ░  ▒   ▒▒ ░   ░  "
echo "                                    ░   ▒    ░ ░  ░ ░      ░     ░   ▒    ░   "
echo "                                        ░  ░   ░           ░         ░  ░   "
echo "                                             ░     "





python3 /home/ubuntu/Desktop/cric3/BTC.py &
python3 /home/ubuntu/Desktop/cric3/ETH.py &
python3 /home/ubuntu/Desktop/cric3/BNB.py &
python3 /home/ubuntu/Desktop/cric3/XRP.py &
python3 /home/ubuntu/Desktop/cric3/ADA.py &
python3 /home/ubuntu/Desktop/cric3/SOL.py &
python3 /home/ubuntu/Desktop/cric3/DOGE.py &
python3 /home/ubuntu/Desktop/cric3/MATIC.py &
python3 /home/ubuntu/Desktop/cric3/DOT.py &
python3 /home/ubuntu/Desktop/cric3/DAI.py &
python3 /home/ubuntu/Desktop/cric3/SHIB.py &
python3 /home/ubuntu/Desktop/cric3/TRX.py &
python3 /home/ubuntu/Desktop/cric3/AVAX.py &
python3 /home/ubuntu/Desktop/cric3/UNI.py &
python3 /home/ubuntu/Desktop/cric3/WBTC.py &
python3 /home/ubuntu/Desktop/cric3/LEO.py &
python3 /home/ubuntu/Desktop/cric3/LTC.py &
python3 /home/ubuntu/Desktop/cric3/ATOM.py &
python3 /home/ubuntu/Desktop/cric3/LINK.py &
python3 /home/ubuntu/Desktop/cric3/ETC.py &
python3 /home/ubuntu/Desktop/cric3/XLM.py &
python3 /home/ubuntu/Desktop/cric3/FTT.py &
python3 /home/ubuntu/Desktop/cric3/NEAR.py &
python3 /home/ubuntu/Desktop/cric3/CRO.py &
python3 /home/ubuntu/Desktop/cric3/XMR.py &
python3 /home/ubuntu/Desktop/cric3/ALGO.py &
python3 /home/ubuntu/Desktop/cric3/BCH.py &
python3 /home/ubuntu/Desktop/cric3/LUNC.py &
python3 /home/ubuntu/Desktop/cric3/QNT.py &
python3 /home/ubuntu/Desktop/cric3/FLOW.py &
python3 /home/ubuntu/Desktop/cric3/VET.py &
python3 /home/ubuntu/Desktop/cric3/TON.py &
python3 /home/ubuntu/Desktop/cric3/APE.py &
python3 /home/ubuntu/Desktop/cric3/FIL.py &
python3 /home/ubuntu/Desktop/cric3/ICP.py &
python3 /home/ubuntu/Desktop/cric3/HBAR.py &
python3 /home/ubuntu/Desktop/cric3/EGLD.py &
python3 /home/ubuntu/Desktop/cric3/XTZ.py &
python3 /home/ubuntu/Desktop/cric3/MANA.py &
python3 /home/ubuntu/Desktop/cric3/SAND.py &
python3 /home/ubuntu/Desktop/cric3/CHZ.py &
python3 /home/ubuntu/Desktop/cric3/EOS.py &
python3 /home/ubuntu/Desktop/cric3/AAVE.py &
python3 /home/ubuntu/Desktop/cric3/THETA.py &
python3 /home/ubuntu/Desktop/cric3/AXS.py &
python3 /home/ubuntu/Desktop/cric3/USDP.py &
python3 /home/ubuntu/Desktop/cric3/OKB.py &
python3 /home/ubuntu/Desktop/cric3/BSV.py &
python3 /home/ubuntu/Desktop/cric3/TUSD.py &
python3 /home/ubuntu/Desktop/cric3/MKR.py &
python3 /home/ubuntu/Desktop/cric3/KCS.py &
python3 /home/ubuntu/Desktop/cric3/ZEC.py &
python3 /home/ubuntu/Desktop/cric3/USDD.py &
python3 /home/ubuntu/Desktop/cric3/HT.py &
python3 /home/ubuntu/Desktop/cric3/XEC.py &
python3 /home/ubuntu/Desktop/cric3/MIOTA.py &
python3 /home/ubuntu/Desktop/cric3/BTT.py &
python3 /home/ubuntu/Desktop/cric3/USDN.py &
python3 /home/ubuntu/Desktop/cric3/CAKE.py &
python3 /home/ubuntu/Desktop/cric3/GRT.py &
python3 /home/ubuntu/Desktop/cric3/NEO.py &
python3 /home/ubuntu/Desktop/cric3/HNT.py &
python3 /home/ubuntu/Desktop/cric3/KLAY.py &
python3 /home/ubuntu/Desktop/cric3/FTM.py &
python3 /home/ubuntu/Desktop/cric3/PAXG.py &
python3 /home/ubuntu/Desktop/cric3/SNX.py &
python3 /home/ubuntu/Desktop/cric3/RUNE.py &
python3 /home/ubuntu/Desktop/cric3/NEXO.py &
python3 /home/ubuntu/Desktop/cric3/GT.py &
python3 /home/ubuntu/Desktop/cric3/DASH.py &
python3 /home/ubuntu/Desktop/cric3/CRV.py &
python3 /home/ubuntu/Desktop/cric3/BAT.py &
python3 /home/ubuntu/Desktop/cric3/ENJ.py &
python3 /home/ubuntu/Desktop/cric3/LDO.py &
python3 /home/ubuntu/Desktop/cric3/STX.py &
python3 /home/ubuntu/Desktop/cric3/KAVA.py &
python3 /home/ubuntu/Desktop/cric3/COMP.py &
python3 /home/ubuntu/Desktop/cric3/ZIL.py &
python3 /home/ubuntu/Desktop/cric3/FEI.py &
python3 /home/ubuntu/Desktop/cric3/RVN.py &
python3 /home/ubuntu/Desktop/cric3/MINA.py &
python3 /home/ubuntu/Desktop/cric3/WAVES.py &
python3 /home/ubuntu/Desktop/cric3/XDC.py &
python3 /home/ubuntu/Desktop/cric3/USDTC.py &
python3 /home/ubuntu/Desktop/cric3/GMT.py &
python3 /home/ubuntu/Desktop/cric3/TWT.py &
python3 /home/ubuntu/Desktop/cric3/LRC.py &
python3 /home/ubuntu/Desktop/cric3/DCR.py &
python3 /home/ubuntu/Desktop/cric3/CVX.py &
python3 /home/ubuntu/Desktop/cric3/CSPR.py &
python3 /home/ubuntu/Desktop/cric3/XEM.py &
python3 /home/ubuntu/Desktop/cric3/KSM.py &
python3 /home/ubuntu/Desktop/cric3/CELO.py &
python3 /home/ubuntu/Desktop/cric3/BTG.py &
python3 /home/ubuntu/Desktop/cric3/ENS.py &
python3 /home/ubuntu/Desktop/cric3/1INCH.py &
python3 /home/ubuntu/Desktop/cric3/HOT.py &
python3 /home/ubuntu/Desktop/cric3/LUNA.py &
python3 /home/ubuntu/Desktop/cric3/RSR.py &
python3 /home/ubuntu/Desktop/cric3/BNX.py &
python3 /home/ubuntu/Desktop/cric3/GUSD.py &
python3 /home/ubuntu/Desktop/cric3/ROSE.py &
python3 /home/ubuntu/Desktop/cric3/YFI.py &
python3 /home/ubuntu/Desktop/cric3/QTUM.py &
python3 /home/ubuntu/Desktop/cric3/AR.py &
python3 /home/ubuntu/Desktop/cric3/ANKR.py &
python3 /home/ubuntu/Desktop/cric3/GNO.py &
python3 /home/ubuntu/Desktop/cric3/GALA.py &
python3 /home/ubuntu/Desktop/cric3/TFUEL.py &
python3 /home/ubuntu/Desktop/cric3/KDA.py &
python3 /home/ubuntu/Desktop/cric3/IOTX.py &
python3 /home/ubuntu/Desktop/cric3/GLM.py &
python3 /home/ubuntu/Desktop/cric3/BTRST.py &
python3 /home/ubuntu/Desktop/cric3/JST.py &
python3 /home/ubuntu/Desktop/cric3/CEL.py &
python3 /home/ubuntu/Desktop/cric3/POLY.py &
python3 /home/ubuntu/Desktop/cric3/ONE.py &
python3 /home/ubuntu/Desktop/cric3/HIVE.py &
python3 /home/ubuntu/Desktop/cric3/OMG.py &
python3 /home/ubuntu/Desktop/cric3/LPT.py &
python3 /home/ubuntu/Desktop/cric3/ZRX.py &
python3 /home/ubuntu/Desktop/cric3/BAL.py &
python3 /home/ubuntu/Desktop/cric3/FLUX.py &
python3 /home/ubuntu/Desktop/cric3/IOST.py &
python3 /home/ubuntu/Desktop/cric3/ICX.py &
python3 /home/ubuntu/Desktop/cric3/BORA.py &
python3 /home/ubuntu/Desktop/cric3/AMP.py &
python3 /home/ubuntu/Desktop/cric3/XYM.py &
python3 /home/ubuntu/Desktop/cric3/SRM.py &
python3 /home/ubuntu/Desktop/cric3/KNC.py &
python3 /home/ubuntu/Desktop/cric3/ONT.py &
python3 /home/ubuntu/Desktop/cric3/OP.py &
python3 /home/ubuntu/Desktop/cric3/GLMR.py &
python3 /home/ubuntu/Desktop/cric3/CHSB.py &
python3 /home/ubuntu/Desktop/cric3/STORJ.py &
python3 /home/ubuntu/Desktop/cric3/WAXP.py &
python3 /home/ubuntu/Desktop/cric3/SC.py &
python3 /home/ubuntu/Desktop/cric3/WOO.py &
python3 /home/ubuntu/Desktop/cric3/ZEN.py &
python3 /home/ubuntu/Desktop/cric3/XCH.py &
python3 /home/ubuntu/Desktop/cric3/SXP.py &
python3 /home/ubuntu/Desktop/cric3/SUSHI.py &
python3 /home/ubuntu/Desktop/cric3/IMX.py &
python3 /home/ubuntu/Desktop/cric3/MXC.py &
python3 /home/ubuntu/Desktop/cric3/AUDIO.py &
python3 /home/ubuntu/Desktop/cric3/NFT.py &
python3 /home/ubuntu/Desktop/cric3/UMA.py &
python3 /home/ubuntu/Desktop/cric3/PLA.py &
python3 /home/ubuntu/Desktop/cric3/SKL.py &
python3 /home/ubuntu/Desktop/cric3/ABBC.py &
python3 /home/ubuntu/Desktop/cric3/SCRT.py &
python3 /home/ubuntu/Desktop/cric3/SLP.py &
python3 /home/ubuntu/Desktop/cric3/DGB.py &
python3 /home/ubuntu/Desktop/cric3/ELON.py &
python3 /home/ubuntu/Desktop/cric3/INJ.py &
python3 /home/ubuntu/Desktop/cric3/VGX.py &
python3 /home/ubuntu/Desktop/cric3/CKB.py &
python3 /home/ubuntu/Desktop/cric3/CVC.py &
python3 /home/ubuntu/Desktop/cric3/LSK.py &
python3 /home/ubuntu/Desktop/cric3/VLX.py &
python3 /home/ubuntu/Desktop/cric3/PUNDIX.py &
python3 /home/ubuntu/Desktop/cric3/COTI.py &
python3 /home/ubuntu/Desktop/cric3/KEEP.py &
python3 /home/ubuntu/Desktop/cric3/DAO.py &
python3 /home/ubuntu/Desktop/cric3/REN.py &
python3 /home/ubuntu/Desktop/cric3/MED.py &
python3 /home/ubuntu/Desktop/cric3/RNDR.py &
python3 /home/ubuntu/Desktop/cric3/CEEK.py &
python3 /home/ubuntu/Desktop/cric3/REEF.py &
python3 /home/ubuntu/Desktop/cric3/EWT.py &
python3 /home/ubuntu/Desktop/cric3/PEOPLE.py &
python3 /home/ubuntu/Desktop/cric3/BTCST.py &
python3 /home/ubuntu/Desktop/cric3/WIN.py &
python3 /home/ubuntu/Desktop/cric3/NU.py &
python3 /home/ubuntu/Desktop/cric3/CELR.py &
python3 /home/ubuntu/Desktop/cric3/SYS.py &
python3 /home/ubuntu/Desktop/cric3/ONG.py &
python3 /home/ubuntu/Desktop/cric3/XNO.py &
python3 /home/ubuntu/Desktop/cric3/REQ.py &
python3 /home/ubuntu/Desktop/cric3/DAG.py &
python3 /home/ubuntu/Desktop/cric3/ORBS.py &
python3 /home/ubuntu/Desktop/cric3/SPELL.py &
python3 /home/ubuntu/Desktop/cric3/RLC.py &
python3 /home/ubuntu/Desktop/cric3/OCEAN.py &
python3 /home/ubuntu/Desktop/cric3/API3.py &
python3 /home/ubuntu/Desktop/cric3/SNT.py &
python3 /home/ubuntu/Desktop/cric3/TRIBE.py &
python3 /home/ubuntu/Desktop/cric3/ARDR.py &
python3 /home/ubuntu/Desktop/cric3/PYR.py &
python3 /home/ubuntu/Desktop/cric3/FX.py &
python3 /home/ubuntu/Desktop/cric3/UOS.py &
python3 /home/ubuntu/Desktop/cric3/POWER.py &
python3 /home/ubuntu/Desktop/cric3/ACA.py &
python3 /home/ubuntu/Desktop/cric3/PROM.py &
python3 /home/ubuntu/Desktop/cric3/DENT.py &
python3 /home/ubuntu/Desktop/cric3/CHR.py &
python3 /home/ubuntu/Desktop/cric3/MX.py &
python3 /home/ubuntu/Desktop/cric3/%launcher%


